import pandas as pd

oef_p = pd.read_csv(r'C:\Users\Slaye\Documents\KSU\Research_F22\datasets\oef_p0.csv')
oef_hoa = pd.read_csv(r'C:\Users\Slaye\Documents\KSU\Research_F22\datasets\oef_hoa0.csv')
oef_ts = pd.read_csv(r'C:\Users\Slaye\Documents\KSU\Research_F22\datasets\oef_ts0.csv')

'''Organizing terrorist groups into more generalized groups.'''
#Operation Freedom Eagle - OEF Philippines
oef_p['gname'] = oef_p['gname'].replace(["Left-wing extremists",
                                         "Aniban ng Ayaw sa Komunista (ANAK) ", 
                                         "Partido Marxista-Leninista ng Pilipinas (PMLP)",
                                         "Communists",
                                         "Alex Boncayao Brigade (ABB)",
                                         "Magahat Militia",
                                         "New Indigenous People's Army",
                                         "National Democratic Front-Bicol (NDF-Bicol)",
                                         "Bangsamoro National Liberation Army"], 
                                        ["New People's Army (NPA)", 
                                         "New People's Army (NPA)", 
                                         "New People's Army (NPA)",
                                         "New People's Army (NPA)",
                                         "New People's Army (NPA)",
                                         "New People's Army (NPA)",
                                         "New People's Army (NPA)",
                                         "New People's Army (NPA)",
                                         "New People's Army (NPA)",])

oef_p['gname'] = oef_p['gname'].replace(["Kilafah Islamic Movement", 
                                         "Jundul Khilafah (Philippines)", 
                                         "Alcubar group",
                                         "East Asia Division of the Islamic State",
                                         "Al-Khobar",
                                         "Jemaah Islamiya (JI)",
                                         "Maute Group",
                                         "Muslim extremists",
                                         "Muslim Separatists",
                                         "Ansar Al-Khilafa (Philippines)",
                                         "Islamic State of Iraq and the Levant (ISIL)"], 
                                        ["Islamic Extremists",
                                         "Islamic Extremists",
                                         "Islamic Extremists",
                                         "Islamic Extremists",
                                         "Islamic Extremists",
                                         "Islamic Extremists",
                                         "Islamic Extremists",
                                         "Islamic Extremists",
                                         "Islamic Extremists",
                                         "Islamic Extremists",
                                         "Islamic Extremists"])

oef_p['gname'] = oef_p['gname'].replace(["Moro Ghuraba",
                                         "Moro National Liberation Front (MNLF)",
                                         "Bangsamoro Islamic Freedom Movement (BIFM)",
                                         "Moro Islamic Liberation Front (MILF)"],
                                        ["Moro Insurgents",
                                         "Moro Insurgents",
                                         "Moro Insurgents",
                                         "Moro Insurgents"])


oef_p['gname'] = oef_p['gname'].replace(["Rebels", 
                                         "Muslim Rebels", 
                                         "Gunmen",
                                         "Farmer's Movement of the Philippines (KMP)",
                                         "Pentagon Kidnap Group",
                                         "Young Officer Union of the New Generation and Reformist Armed Forces of the Philippines (YOU-RAFP)",
                                         "Kawal ng Pilipinas (Soldier of the Philippines)"], 
                                        ["Unknown",
                                         "Unknown",
                                         "Unknown",
                                         "Unknown",
                                         "Unknown",
                                         "Unknown",
                                         "Unknown"])


#Operation Enduring Freedom - Horn of Africa
oef_hoa['gname'] = oef_hoa['gname'].replace(["Muslim extremists", 
                                             "Sunni Muslim extremists", 
                                             "Somali Islamic Front",
                                             "Hizbul al Islam (Somalia)",
                                             "Raskamboni Movement",
                                             "Al-Qaida",
                                             "Jabha East Africa",
                                             "Sudanese Islamic Youth Movement",
                                             "Islamic Courts Union (ICU)",
                                             "Al-Ittihaad al-Islami (AIAI)",
                                             "Islamic Party (Somalia)",
                                             "Islamic State of Iraq and the Levant (ISIL)",
                                             "Islamic Tendency"],
                                            ["Islamic Extremists",
                                             "Islamic Extremists",
                                             "Islamic Extremists",
                                             "Islamic Extremists",
                                             "Islamic Extremists",
                                             "Islamic Extremists",
                                             "Islamic Extremists",
                                             "Islamic Extremists",
                                             "Islamic Extremists",
                                             "Islamic Extremists",
                                             "Islamic Extremists",
                                             "Islamic Extremists",
                                             "Islamic Extremists"])

oef_hoa['gname'] = oef_hoa['gname'].replace(["Tribesmen", 
                                             "Misseriya Arab Tribesmen", 
                                             "Merille Militia",
                                             "Shabelle Valley militia",
                                             "Zaghawa extremists",
                                             "Abbala extremists",
                                             "Samri militia",
                                             "Bedouin Movement (Sudan)",
                                             "Ahlu-sunah Wal-jamea (Somalia)",
                                             "Liberation and Justice Movement (LJM)",
                                             "Pokot extremists",
                                             "Habr Gedir Clan",
                                             "Supporters of Sultan Abd-al-Bagi",
                                             "Abu Tira (Central Reserve Forces)",
                                             "Gumuz militia",
                                             "Hamza Combat Group against Atheism and Heresy",
                                             "Mungiki Sect",
                                             "Sungu Sungu",
                                             "Sudan People's Liberation Movement - North",
                                             "Sudan Liberation Movement",
                                             "Sudan People's Liberation Army (SPLA)",
                                             "Sudan Revolutionary Front (SRF)",
                                             "Justice and Equality Movement (JEM)",
                                             "Sabaot Land Defense Force (SLDF)",
                                             "Sudan Liberation Army-Minni Minawi (SLA-MM)",
                                             "South Sudan Liberation Army (SSLA)",
                                             "Democratic Movement for the Liberation of the Eritrean Kunamas (DMLEK)",
                                             "23 May Democratic Alliance (Algeria)",
                                             "People's Democratic Struggle Movement",
                                             "National Redemption Front",
                                             "Benishangul Gumuz People's Liberation Movement",
                                             "Awdal Regional Administration Army (ARAA)",
                                             "Murle Tribe",
                                             "Lord's Resistance Army (LRA)",
                                             "Amhara militia"], 
                                            ["Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes",
                                             "Regional Militias/Tribes"])

oef_hoa['gname'] = oef_hoa['gname'].replace(["Patriotic Ginbot 7 Movement for Unity and Democracy (PGMUD)", 
                                             "Sudanese People's Front",
                                             "Political Organization",
                                             "Oromo Liberation Front",
                                             "Ogaden National Liberation Front (ONLF)",
                                             "Mombasa Republican Council (MRC)",
                                             "Tigray Peoples Liberation Front (TPLF)",
                                             "Coalition for Unity and Democracy (CUD)",
                                             "Afar Revolutionary Democratic Unity Front",
                                             "Eritrean Salvation Front (ESF)",
                                             "Red Sea Afar Democratic Organization (RSADO)",
                                             "Front for the Restoration of Unity and Democracy", 
                                             "All Ethiopian Unity Party (AEUP)"],
                                            ["Political Organization",
                                             "Political Organization",
                                             "Political Organization",
                                             "Political Organization",
                                             "Political Organization",
                                             "Political Organization",
                                             "Political Organization",
                                             "Political Organization",
                                             "Political Organization",
                                             "Political Organization",
                                             "Political Organization",
                                             "Political Organization",
                                             "Political Organization"])

oef_hoa['gname'] = oef_hoa['gname'].replace(["Gunmen", 
                                             "Militia Members", 
                                             "Government Supporters",
                                             "Pirates",
                                             "Rebels",
                                             "Tepi Youth"],
                                            ["Unknown",
                                             "Unknown",
                                             "Unknown",
                                             "Unknown",
                                             "Unknown",
                                             "Unknown"])


#Operation Juniper Shield - OEF Trans-Sahara
oef_ts['gname'] = oef_ts['gname'].replace(["Algerian Islamic Extremists", 
                                           "Muslim extremists", 
                                           "Islamist extremists",
                                           "Armed Islamic Group (GIA)",
                                           "Salafia Jihadia",
                                           "Jihadi-inspired extremists",
                                           "Salafi Extremists",
                                           "Jund al-Khilafah (Tunisia)",
                                           "Sunni Muslim extremists",
                                           "Movement for Oneness and Jihad in West Africa (MUJAO)",
                                           "Jund al-Khilafa",
                                           "Tripoli Province of the Islamic State",
                                           "Islamic Movement (Nigeria)",
                                           "Okba Ibn Nafaa Brigade",
                                           "Macina Liberation Front (FLM)",
                                           "Ansaru (Jama'atu Ansarul Muslimina Fi Biladis Sudan)",
                                           "Ansar al-Sharia (Tunisia)",
                                           "El-Feth katibat",
                                           "Algeria Province of the Islamic State",
                                           "Islamic State of Iraq and the Levant (ISIL)",
                                           "Ed'daoua Es'salafia Lilqadha",
                                           "Al-Qaida",
                                           "Aibed Er-Rahman katibet",
                                           "Al-Furqan (Tunisia)",
                                           "Draa El Mizan Seriat",
                                           "Al-Mua'qi'oon Biddam Brigade (Those who Sign with Blood)",
                                           "Ansar al-Dine (Mali)",
                                           "Ansar al-Islam (Burkina Faso)",
                                           "Islamic State in the Greater Sahara (ISGS)",
                                           "Salafi Daawa Group"],
                                          ["Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists",
                                           "Islamic Extremists"])

oef_ts['gname'] = oef_ts['gname'].replace(["Salafist Group for Preaching and Fighting (GSPC)"],
                                          ["Al-Qaida in the Islamic Maghreb (AQIM)"])

oef_ts['gname'] = oef_ts['gname'].replace(["Ijaw extremists", 
                                           "Indigenous People of Biafra (IPOB)", 
                                           "Tuareg extremists",
                                           "Tiv Militia",
                                           "Dogon extremists",
                                           "Dozo militia",
                                           "Jukun militia",
                                           "Niger Delta extremists",
                                           "Nyandan militia",
                                           "Irigwe Militia",
                                           "Bachama extremists",
                                           "Ambazonia Tigers",
                                           "Atyap militia",
                                           "Niger Delta Vigilante (NDV)",
                                           "Concerned Militant Leaders (CML)",
                                           "Tarok Militia",
                                           "Dan Na Ambassagou",
                                           "Seleka",
                                           "Ambazonia Defense Forces (ADF)",
                                           "Movement of Democratic Forces of Casamance",
                                           "Azawad National Liberation Movement (MNLA)",
                                           "Niger Delta Avengers (NDA)",
                                           "High Council for the Unity of Azawad (HCUA)",
                                           "Military Command Council for the Salvation of the Republic (CCSMR)",
                                           "United Front for Democratic Change (FUC)",
                                           "Niger Delta Liberation Force (NDLF)-Nigeria",
                                           "National Alliance (Chad)",
                                           "Union of Forces for Democracy and Development (UFDD)",
                                           "Niger Delta People's Volunteer Force (NDPVF)",
                                           "Bassa Kwomu extremists",
                                           "Bini-Oru",
                                           "Movement of Niger People for Justice (MNJ)",
                                           "Movement for the Actualization of the Sovereign State of Biafra (MASSOB)",
                                           "Niger Delta Forest Army (NDFA)",
                                           "Rally of Democratic Forces (RAFD)",
                                           "National Committee for the Restoration of Democracy and State (CNRDR)",
                                           "Union of Chadian Forces (UFNT)",
                                           "Justice and Equality Movement (JEM)",
                                           "National Committee for the Salvation of the People",
                                           "Red Egbesu Water Lions",
                                           "Delta Democratic Militia",
                                           "Tuareg Guerrillas",
                                           "Al-Sunna wal Jamma",
                                           "Ombatse Cult",
                                           "Anti-Balaka Militia",
                                           "Koglweogo",
                                           "Biafra Zionist Movement (BZM)",
                                           "Itsekiri",
                                           "Movement for the Restoration of the Independence of Southern Cameroons",
                                           "Council for Justice in Azawad",
                                           "Coordination of Azawad Movements (CMA)",
                                           "Niger Delta Greenland Justice Mandate (NDGJM)",
                                           "Ambazonia Restoration Forces (ARF)",
                                           "Democratic Front of the Central African People (FDPC)",
                                           "The Joint Revolutionary Council",
                                           "Arab Movement of Azawad (MAA)",
                                           "Africa Marine Commando",
                                           "Civilian Joint Task Force (JTF)",
                                           "Urhobo Gbagbako",
                                           "23 May Democratic Alliance (Algeria)",
                                           "Koluama Seven Brothers",
                                           "People's Democratic Party (PDP)",
                                           "Odua Peoples' Congress (OPC)",
                                           "Urhobo Revolutionary Army",
                                           "Movement for the Emancipation of the Niger Delta (MEND)",
                                           "Niger Delta Freedom Fighters (NDDF)",
                                           "Niger Delta Justice Defense Group (NDJDG)",
                                           "Janjaweed",
                                           "Intelligence Force of Oku",
                                           "Gugama Youth Federation",
                                           "Movement for Democracy and Justice in Chad (MDJT)",
                                           "Movement for the Salvation of Azawad (MSA)",
                                           "Youth Movement for the Total Liberation of Azawad",
                                           "Reformed Niger Delta Avengers (RNDA)",
                                           "Self-Defense Group of Imghad Tuaregs and Allies (GATIA)",
                                           "Egbema National Front",
                                           "Return, Reclamation, Rehabilitation (3R)",
                                           "Berom Militants"],
                                          ["Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes",
                                           "Regional Militias/Tribes"])

oef_ts['gname'] = oef_ts['gname'].replace(["Separatists", 
                                           "Gunmen", 
                                           "Militants",
                                           "Muslim Militants",
                                           "Rebels",
                                           "Extremists",
                                           "Insurgents",
                                           "Mouhajiroune Brigade",
                                           "Red Scorpion",
                                           "Strikers",
                                           "The 78 Unemployed",
                                           "Red Dragons",
                                           "Political Organization",
                                           "Freedom Eagles of Africa",
                                           "Tribesmen",
                                           "Sudanese Rebels"],
                                          ["Unknown",
                                           "Unknown",
                                           "Unknown",
                                           "Unknown",
                                           "Unknown",
                                           "Unknown",
                                           "Unknown",
                                           "Unknown",
                                           "Unknown",
                                           "Unknown",
                                           "Unknown",
                                           "Unknown",
                                           "Unknown",
                                           "Unknown",
                                           "Unknown",
                                           "Unknown"])

#Checking group frequencies
table1 = oef_p.gname.value_counts()
table2 = oef_hoa.gname.value_counts()
table3 = oef_ts.gname.value_counts()



'''Exporting the three seperate subsets of data'''
oef_p.to_csv(r'C:\Users\Slaye\Documents\KSU\Research_F22\datasets\oef_p.csv')
oef_hoa.to_csv(r'C:\Users\Slaye\Documents\KSU\Research_F22\datasets\oef_hoa.csv')
oef_ts.to_csv(r'C:\Users\Slaye\Documents\KSU\Research_F22\datasets\oef_ts.csv')
